### ISSUE TITLE
Noted during Nero3D Stream part 6

### ISSUE THREAD

**Issue by HumbleDeer** [VzBoT3D/docs#55]
- [x] #88 
- [x] #74 Printhead page typos
- [x] #26 
- [ ] #46 Could be used for Hot end / goliath
- [x] #90
- [x] #91
- [ ] #39 Belt routing / motor designation
---
https://www.youtube.com/watch?v=9ZZNjZha22Q

### Routing

1. How does the umbilical cord route?
  + Looks like it's along the cable guide
  + then on the back side of the back panel outside of the printer, in to the electronics box)
  + Does this use a printed part? 
  + Looks like the top hat should have a cutout for the wiring loom to pass through; is the wiring loom protected?

2. How does the CPAP tube route?
  + Ties to the cable guide
  + Passes into the enclosure in front of the rear top extrusion
  + Goes into the round hole under the extrusion, at an angle
    - Does this use some printed part to protect the tube?

### Other CPAP things

* Does the umbilical cord get a protective sleeve, liek a braided sleeve?
* How does one attach the wires to the CPAP tube? Zip ties, or velcro ties? 
    _The CPAP tube is very fragile!_
* Specifically for Mellow Vz330/Vz235: Perhaps the CPAP printed part at the print head could have a threaded section to thread the CPAP tube on to?

Relates to issue #88 

---

## Typos on printhead page ✅FIXED

https://docs.vzbot.org/vz330_mellow/gantry/printhead

* Upper duct CPAP C clamp (picture)
* Goliath 2510 fan duct (picture)
* What screws for the hot end cooling fan, and what orientation?

![image](https://github.com/VzBoT3D/docs/assets/16231288/6c5f82c3-1a42-4e64-8bb2-c158c3b4cd3a)

---

## Hot end / goliath

* Integrate newest Goliath docs into the Vz330/Vz235 Print Head docs, to clarify those sections.
* Put the Goliath Assembly link-through at the top of the Goliath index page
* Slim down the Goliath index page?
* Clarify that some of the pictures are for water cooling based setups; 
    air cooled setup doesn't allow all wire routing options

---

## Print head

* Vz-Printhead has no zip tie points, unlike the older EVA based printhead. Does the printed Vz-Printhead have any zip tie points?

## General comments

* Pictures
    + > I really wish there were more pictures of assembled machines!
    + > Get someone in the Discord server whos VZ is super pimped to take pictures of all the sub assemblies
        Probably better to have someone who's not yet finished taking those pictures?
    + Youtube chatter mentioned: github.com/VzBoT3D/VzBoT-Vz330/tree/master/Gallery
    
## Gantry parts exchange

https://docs.vzbot.org/vz330_mellow/gantry/change_parts

(noted during self exploration)

Clarify why one needs to exchange these parts, and make the guide more compact.

**Comment by DerDackel** [comment]
Better document endstop mounting/soldering, see also #26 

Explain concept of CoreXY, motor axis naming (Do we hafve a section for that already?)

Stepper wire routing for the front steppers - under the top extrusion or downwards along the bottom plate?

**Comment by HumbleDeer** [comment]
## Belt routing / motor designation

* Clarify which motors are  X/X1 and Y/Y1.
    The Vz235 docs have a diagram; rotate this 180° to get the Vz330 diagram.  
* Add a label to the diagrams what's front and back

## 5160 Stepper driver section

* Split the stepper drivers into its own section.

* Move picture showing Black, Green, Red and Blue wires to the 5160 Stepper Driver section
* Move bridges between mainboard and 5160hv to the 5160 section / its future dedicated page

### Motors:

* Clarify that the stepper motor wires need ferrules
* Clarify how to find A B C D, or which ones go to which phase (maybe link to Voron docs on finding the motor phases?)
    Black Green Red Blue, top to bottom. There's a picture showing this on the page, elsewhere
* @DerDackel said: 
    > LDO has been fairly consistent. Red+Blue should be A, Green+Black should be B

## General issues

Seriously, the entire docs page on the Mellow Super8 needs a restructuring. 

* Mellow has docs on their boards too: https://mellow-3d.github.io/
* We need to rebuild this to be based on a Motherboard, and specify it's a Super8. 
* Slim down the Motherboard section to things specifically just the motherboard
* Split sections down into smaller chunks:
    + Motherboard specifics setup
    + Stepper driver setup (& Stepper motor wiring?)
    + Power wiring
    + Components
    
### FAQ additions

#### Does the VzBoT have a bed probe?

#### Does the VzBoT have a filament sensor?

**Comment by 1980alexGS** [comment]
From the start of the stream (I’ll try to comment in order that the questions arise). Where I mention “my kit”, I mean the Mellow 330 kit (black) that I received in the last month.

**Mains inlet wiring**: docs need a diagram of this, showing the switch. Small red/black wires with push-on spade terminals were included with my kit, also some fork terminals that fit the power supply and the SSR, and lots of blue/red wire. It is probably possible to put it together without the use of WAGOs or additional DIN-mounted terminals. You could fit two of the fork terminals to each power supply AC input, and use one to bring the power in from the inlet/switch, the other to take the power to the SSD or to the other power supply.

However, I wanted brown/blue/green-yellow AC wiring colours (standard for AC wiring in most countries), so I cut up the black IEC power cord supplied (EU plug which doesn’t fit outlets here anyway). I used a DIN-mounted terminal block (purchased separately) to wire in the SSR/heated bed. I purchased about 25 crimp fork terminals that fit the power supplies and Super 8 board.

**Solid State Relay clip** - metal clip was included on the SSR in my kit.
If you don’t have a clip, surely a good option is to drill holes in the aluminium back panel and screw the SSR directly onto it. Either use screws+nuts, or tap threads, or use self-tapping screws (depending on what you have available).

**Powering the Pi** - the Super 8 section of docs.vzbot shows the use of the ST-LINK to USB adapter. This was included with my kit, in the Super 8 box.

**Cable for Z stepper motor** - this was tucked into the foam in the top layer of my kit’s packaging.

**Bowden tube and tool head wiring passes out through the slot in the tophat panel** - I chose to purchase woven sheath for the motor wiring (protects it where it passes through the panel and also hides the wiring colours) and also a large woven sheath for the tool head wiring.

**Cable guide/CPAP tube guide has the ‘teeth’ facing backwards** - the CPAP tube goes on the front, the cables/PTFE tube on the back between the ‘teeth’. In the stream, we see it going on the wrong way…

**Hotend fan** - to use M3x14mm screws supplied, drill out the holes to 2.5mm. The fan cable needs to be extended.

**Y end stop** - this is actually not shown anywhere in the docs. I think it should be installed at the same time as the gantry. Endstop switches were provided in my kit, in the same box as the SSR bracket and the rubber feet :)

I would like photos of my electronics bay to appear in the docs :) because what’s in the docs is quite different with two SSRs shown, different power supplies, lots of WAGOs, blue and white wires etc. 

Nero3D (Taylor) is a nice guy, I really appreciate how patient/tolerant he is turning out to be during this build.
